# Generated by Django 4.1.3 on 2022-11-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_coach_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Направление')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('photo', models.ImageField(blank=True, upload_to='direction/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('photo', models.ImageField(blank=True, upload_to='subscription/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_coach',
            field=models.BooleanField(default=False, verbose_name='Статус тренера'),
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
