# Generated by Django 4.1.3 on 2022-11-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_direction_schedule_subscription_user_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='title',
            new_name='direction',
        ),
    ]
