# Generated by Django 4.1.3 on 2022-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_schedule_date_schedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='days',
            field=models.ManyToManyField(to='main.days'),
        ),
    ]
