# Generated by Django 4.1.3 on 2022-11-16 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_days_schedule_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='days',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=django.utils.timezone.now, max_length=1, verbose_name='День недели'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
