# Generated by Django 4.1.3 on 2022-11-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_schedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='content',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='title',
        ),
        migrations.AddField(
            model_name='subscription',
            name='sessions',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='time',
            field=models.CharField(choices=[('0', 'Утро'), ('1', 'Вечер')], default=0, max_length=1, verbose_name='Время'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('0', 'Воскресенье')], max_length=1, verbose_name='День недели'),
        ),
    ]
