# Generated by Django 4.1.3 on 2022-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Отображение'),
        ),
    ]
