# Generated by Django 4.1.3 on 2022-11-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_direction_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='notes',
            field=models.CharField(blank=True, max_length=50, verbose_name='Примечание'),
        ),
    ]
