# Generated by Django 4.1.3 on 2022-11-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_schedule_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
    ]
